FORM_DEFINITIONS = {
    "A": {
        "title": "Form A: Interacting with humans, collecting primary data and mixed methods studies",
        "templates": [
            ("Personal Impact Assessment Form And POPIA Consent Template", "docs/PIIA, POPIA consent and justification of collection of personal information.docx"),
            ("Participation Information Sheet & Consent Form Template", "docs/JBSREC_informed_consent_template_Jan_2019.docx"),
            ("Permission/Waiver and Declaration", "docs/JBSREC_apstone_Consulting_Project_Waiver_and_Declaration.docx"),
            ("Permission to Conduct Research", "docs/Permission letter template _Jan 2026.doc"),
        ],
        "sections": [
            {
                "title": "Before You Start Form A",
                "fields": [
                    {"name": "need_permission", "label": "1. Will you require permission to access the company or organisation?", "type": "radio", "options": ["Yes", "No", "Pending"]},
                    {"name": "permission_letter", "label": "Upload Company Permission Letter(s) (with a letterhead, signed and dated)", "type": "file", "multiple": True, "required": True, "show_when": {"field": "need_permission", "values": ["Yes"]}},
                    {"name": "pending_note", "label": "Upload Pending Note (briefly explain who you contacted and expected timeline)", "type": "file", "required": True, "show_when": {"field": "need_permission", "values": ["Pending"]}},
                    {"name": "has_clearance", "label": "2. Do you have prior ethical clearance from the original study?", "type": "radio", "options": ["Yes", "No"]},
                    {"name": "prior_clearance", "label": "Upload Prior Ethical Clearance Document (Original Study)", "type": "file", "required": True, "show_when": {"field": "has_clearance", "values": ["Yes"]}},
                    {"name": "company_requires_jbs", "label": "3. Will you collect personal information?", "type": "radio", "options": ["Yes", "No"]},
                    {"name": "prior_clearance1", "label": "Upload POPIA Information Letter and Consent Form", "type": "file", "required": True, "show_when": {"field": "company_requires_jbs", "values": ["Yes"]}},
                    {"name": "research_tools_path", "label": "4. Upload Survey / Questionnaire / Focus Group Questions", "type": "file", "required": True},
                    {"name": "proposal_path", "label": "5. Upload Research Proposal", "type": "file", "required": True},
                    {"name": "impact_assessment_path", "label": "6. Upload Personal Impact Assessment Form", "type": "file", "required": True},
                    {"name": "participation_info_sheet", "label": "7. Upload Participation Information Sheet & Consent Form", "type": "file", "required": True},
                ],
            },
            {
                "title": "Section 1: Researcher's Details",
                "fields": [
                    {"name": "applicant_name", "label": "Applicant Name", "type": "text", "required": True},
                    {"name": "student_number", "label": "Student / Staff Number", "type": "text", "required": True},
                    {"name": "institution", "label": "Institution", "type": "text", "default": "University of Johannesburg", "required": True},
                    {"name": "department", "label": "UJ Department and School", "type": "text", "required": True},
                    {"name": "degree", "label": "Degree Registered For", "type": "text", "default": "MBA", "required": True},
                    {"name": "study_title", "label": "Title / Working Title of Study", "type": "text", "required": True},
                    {"name": "mobile", "label": "Mobile Number", "type": "tel", "required": True},
                ],
            },
            {
                "title": "Section 2: Ethical Clearance Aspects And Risk Assessment",
                "fields": [
                    {"name": "data_collection_methods", "label": "1. Ethical Clearance Aspects", "type": "checkboxes", "options": ["Survey", "Focus Groups", "Observations", "Interviews", "Documents"]},
                    {"name": "vulnerable_groups", "label": "2.1 Vulnerable groups", "type": "checkboxes", "options": ["Vulnerable communities", "People under 18 or over 65", "UJ employees or students", "Persons vulnerable in this context", "Non-English-speaking participants", "Researcher's own students", "People living in poverty", "People with little or no education"]},
                    {"name": "vulnerable_other_specify", "label": "Other vulnerable group: specify", "type": "text"},
                    {"name": "research_activity_risks", "label": "2.2 Research activity risk indicators", "type": "checkboxes", "options": ["Disclosure without consent", "Discomfiture beyond normal inconvenience", "Deception or covert observation", "Sensitive or contentious issues", "Prejudicial information", "Intrusive techniques", "Illegal activities", "Personal/social information", "Identifiable available records", "Psychology inventories/scales/tests", "Researcher/data collector risk"]},
                    {"name": "vulnerable_comments_2", "label": "Comments", "type": "textarea"},
                    {"name": "additional_considerations", "label": "2.3 Additional research considerations", "type": "checkboxes", "options": ["Reimbursement or incentives", "Financial costs to participants", "Researcher financial or other involvement", "Conflict of interest", "Conducted on UJ premises", "Uses UJ facilities", "Funded by UJ or UJ-acquired funding"]},
                    {"name": "apply_comments", "label": "Comments", "type": "textarea"},
                    {"name": "risk_rating", "label": "2.4 Rate your project (Low, Medium, High Risk)", "type": "select", "options": ["Low", "Medium", "High"], "required": True},
                    {"name": "risk_justification", "label": "2.4.1 Please justify your risk level", "type": "textarea", "required": True},
                    {"name": "benefits_description", "label": "2.4.2 For medium and high risk, describe the potential benefits of the study", "type": "textarea"},
                    {"name": "risk_mitigation", "label": "2.4.3 For medium and high risk, describe how potential risks will be mitigated against", "type": "textarea"},
                ],
            },
            {
                "title": "Section 3: Proposal Summary Sheet",
                "fields": [
                    {"name": "title_provision", "label": "3.1 Title or provisional title of the research project", "type": "text"},
                    {"name": "abstract", "label": "3.2 Proposal abstract in nontechnical language and statement of research problem", "type": "textarea"},
                    {"name": "questions", "label": "3.3 Research Questions / Hypotheses", "type": "textarea"},
                    {"name": "purpose_objectives", "label": "3.4 Research Purpose and Objectives / Anticipated outcomes", "type": "textarea"},
                ],
            },
            {
                "title": "Section 4: Details of Proposed Research",
                "fields": [
                    {"name": "grant_permission", "label": "4.1 Does your project involve organisations or institutions that need to grant permission for research activities?", "type": "radio", "options": ["No", "Yes"]},
                    {
                        "name": "organisation_permissions",
                        "label": "Organisation permission table",
                        "type": "table",
                        "show_when": {"field": "grant_permission", "values": ["Yes"]},
                        "columns": [
                            {"name": "org_name", "label": "Organisation / institution"},
                            {"name": "org_contact", "label": "Contact person"},
                            {"name": "org_role", "label": "Role in the research"},
                            {"name": "org_permission", "label": "Permission status"},
                        ],
                    },
                    {"name": "researcher_affiliation", "label": "4.2 Are any researchers affiliated with the organisations above?", "type": "radio", "options": ["No", "Yes"]},
                    {"name": "affiliation_details", "label": "Affiliation details", "type": "textarea", "required": True, "show_when": {"field": "researcher_affiliation", "values": ["Yes"]}},
                    {"name": "collective_involvement", "label": "4.3 Does your research involve collectives or communities?", "type": "radio", "options": ["No", "Yes"]},
                    {"name": "collective_details", "label": "Community/collective engagement details", "type": "textarea", "required": True, "show_when": {"field": "collective_involvement", "values": ["Yes"]}},
                    {"name": "is_funded", "label": "4.4 Is your project funded or sponsored?", "type": "radio", "options": ["No", "Yes"]},
                    {
                        "name": "funding_sources",
                        "label": "Funding / sponsorship table",
                        "type": "table",
                        "show_when": {"field": "is_funded", "values": ["Yes"]},
                        "columns": [
                            {"name": "fund_org", "label": "Funding organisation"},
                            {"name": "fund_contact", "label": "Contact person"},
                            {"name": "fund_role", "label": "Role in the research"},
                            {"name": "fund_amount", "label": "Amount / value"},
                        ],
                    },
                    {"name": "indemnity", "label": "4.5 Describe your arrangements regarding indemnity/compensation for adverse events", "type": "textarea"},
                ],
            },
            {
                "title": "Section 5: Methodology",
                "fields": [
                    {"name": "research_paradigm", "label": "5.1 Research Paradigm", "type": "checkboxes", "options": ["Quantitative", "Qualitative", "Mixed Methods"]},
                    {"name": "paradigm_explanation", "label": "Substantiate your choice of paradigm", "type": "textarea"},
                    {"name": "design", "label": "5.2 Research Design / Approach", "type": "textarea"},
                    {"name": "participants_description", "label": "5.3.1 Participant Group Description", "type": "textarea"},
                    {
                        "name": "participant_sampling",
                        "label": "Participant population and sampling table",
                        "type": "table",
                        "columns": [
                            {"name": "population", "label": "Population"},
                            {"name": "sampling_method", "label": "Sampling method"},
                            {"name": "sample_size", "label": "Sample size", "type": "number"},
                            {"name": "inclusion_criteria", "label": "Inclusion criteria", "type": "textarea"},
                        ],
                    },
                    {"name": "duration_timing", "label": "5.3.2 Time required of participants and when data will be collected", "type": "textarea"},
                    {"name": "contact_details_method", "label": "5.3.3 How you will obtain participant contact details", "type": "textarea"},
                    {"name": "conflict_interest", "label": "5.3.4 Conflict of interest or unequal relationship?", "type": "radio", "options": ["No", "Yes"]},
                    {"name": "conflict_explanation", "label": "If yes, give details and explain how it will be mitigated", "type": "textarea", "required": True, "show_when": {"field": "conflict_interest", "values": ["Yes"]}},
                    {"name": "data_methods", "label": "5.4.1 Data collection methods", "type": "checkboxes", "options": ["Questionnaire", "Interview", "Focus Group", "Observation", "Documents", "Other"]},
                    {"name": "questionnaire_details", "label": "5.4.1.1 Questionnaire details: self-designed/existing, permission obtained, and justification", "type": "textarea", "show_when": {"field": "data_methods", "values": ["Questionnaire"]}},
                    {"name": "interview_details", "label": "5.4.1.2 Interview details: type and how interviews will be recorded", "type": "textarea", "show_when": {"field": "data_methods", "values": ["Interview"]}},
                    {"name": "focus_details", "label": "5.4.1.3 Focus group recording details", "type": "textarea", "show_when": {"field": "data_methods", "values": ["Focus Group"]}},
                    {"name": "observation_details", "label": "5.4.1.4 Please describe your observation protocol", "type": "textarea", "show_when": {"field": "data_methods", "values": ["Observation"]}},
                    {"name": "documents_details", "label": "5.4.1.5 What type of documents will be analyzed?", "type": "textarea", "show_when": {"field": "data_methods", "values": ["Documents"]}},
                    {"name": "other_details", "label": "5.4.1.6 Please describe other data collection method(s)", "type": "textarea", "show_when": {"field": "data_methods", "values": ["Other"]}},
                    {"name": "data_collection_procedure", "label": "5.4.2 Describe the data collection procedure", "type": "textarea"},
                    {"name": "data_collectors", "label": "5.4.3 Who will collect the data?", "type": "textarea"},
                    {"name": "intervention", "label": "5.4.4 Will participants be subjected to any intervention?", "type": "radio", "options": ["No", "Yes"]},
                    {"name": "intervention_details", "label": "If yes, explain the intervention in full", "type": "textarea", "required": True, "show_when": {"field": "intervention", "values": ["Yes"]}},
                    {"name": "sensitive_data", "label": "5.4.5 Will sensitive data be used or vulnerable populations be questioned?", "type": "textarea"},
                    {"name": "translator", "label": "5.4.6 Will a translator be required?", "type": "radio", "options": ["No", "Yes"]},
                    {"name": "translator_procedure", "label": "If yes, explain in which way and the procedure that will be followed", "type": "textarea", "required": True, "show_when": {"field": "translator", "values": ["Yes"]}},
                    {"name": "secondary_data", "label": "5.5.1 Will secondary data be used?", "type": "select", "options": ["No", "Yes"]},
                    {"name": "data_type", "label": "5.5.2 Is the data public, private, or both?", "type": "select", "options": ["Public", "Private", "Both"], "show_when": {"field": "secondary_data", "values": ["Yes"]}},
                    {"name": "data_nature", "label": "5.5.3 Nature of the data", "type": "text", "show_when": {"field": "secondary_data", "values": ["Yes"]}},
                    {"name": "data_origin", "label": "5.5.4 Origin/source of research data", "type": "text", "show_when": {"field": "secondary_data", "values": ["Yes"]}},
                    {"name": "access_conditions", "label": "5.5.5 Access conditions", "type": "textarea", "show_when": {"field": "secondary_data", "values": ["Yes"]}},
                    {"name": "personal_info", "label": "5.5.6 Does the database contain personal information/identifiers?", "type": "radio", "options": ["Yes", "No"], "show_when": {"field": "secondary_data", "values": ["Yes"]}},
                    {"name": "personal_info_comment", "label": "5.5.6.1 Specify the personal information/identifiers", "type": "textarea", "required": True, "show_when": {"field": "personal_info", "values": ["Yes"]}},
                    {"name": "data_anonymized", "label": "5.5.7 Has the data been anonymized?", "type": "radio", "options": ["Yes", "No", "Not Applicable"], "show_when": {"field": "secondary_data", "values": ["Yes"]}},
                    {"name": "anonymization_comment", "label": "5.5.7.1 Comment / Justification", "type": "textarea", "show_when": {"field": "secondary_data", "values": ["Yes"]}},
                    {"name": "permission_details", "label": "5.5.8 If private data permission is not already attached, provide permission details", "type": "textarea", "show_when": {"field": "data_type", "values": ["Private", "Both"]}},
                    {"name": "private_permission_file", "label": "5.5.8.1 Upload private permission document", "type": "file", "show_when": {"field": "data_type", "values": ["Private", "Both"]}},
                    {"name": "public_data_description", "label": "5.5.8 What type of public data will be used?", "type": "textarea", "show_when": {"field": "data_type", "values": ["Public", "Both"]}},
                    {"name": "shortcomings_reported", "label": "5.5.9 Will data shortcomings/incompleteness be reported?", "type": "radio", "options": ["Yes", "No"], "show_when": {"field": "secondary_data", "values": ["Yes"]}},
                    {"name": "limitations_reporting", "label": "5.5.10 How will data limitations be reported?", "type": "textarea", "show_when": {"field": "secondary_data", "values": ["Yes"]}},
                    {"name": "methodology_alignment", "label": "5.5.11 Is the research methodology and design aligned with secondary data use?", "type": "radio", "options": ["Yes", "No"], "show_when": {"field": "secondary_data", "values": ["Yes"]}},
                    {"name": "methodology_alignment_comment", "label": "If no, justify your answer", "type": "textarea", "required": True, "show_when": {"field": "methodology_alignment", "values": ["No"]}},
                    {"name": "data_acknowledgment", "label": "5.5.12 How will the original owners of the data be acknowledged?", "type": "textarea", "show_when": {"field": "secondary_data", "values": ["Yes"]}},
                ],
            },
            {
                "title": "Section 6: Ethical Considerations",
                "fields": [
                    {"name": "informed_consent", "label": "6.1 Will informed consent be obtained? Explain the process", "type": "textarea"},
                    {"name": "data_storage", "label": "6.2 Data storage and access to data", "type": "checkboxes", "options": ["Paper-based records kept in secure location", "Computer records access controlled", "Electronic data kept in protected place", "Paper-based data kept for 5 years and destroyed"]},
                    {"name": "study_benefits", "label": "6.3 What are the benefits of the study?", "type": "textarea"},
                    {"name": "participant_risks", "label": "6.4 Description of risks participants may suffer and level of risk", "type": "textarea"},
                    {"name": "adverse_steps", "label": "6.5 Steps to be taken in case of adverse events", "type": "textarea"},
                    {"name": "community_participation", "label": "6.6 Anticipated community participation", "type": "textarea"},
                    {"name": "community_effects", "label": "6.7 Possible adverse effects on the community", "type": "textarea"},
                    {"name": "privacy", "label": "6.8 Data privacy practices applied", "type": "checkboxes", "options": ["Personal identifiers removed", "Encryption", "Use of pseudonyms", "Focus group confidentiality warning"]},
                    {"name": "covering_letter_checklist", "label": "6.9 Covering letter ethical requirements checklist", "type": "checkboxes", "options": ["a) Identity and position of researcher(s)", "b) Purpose of information collection", "c) Selection and procedures", "d) Participant's role", "e) Expected duration", "f) Voluntary participation and no penalty", "g) Benefits", "h) Risks and harm steps", "i) Right to withdraw", "j) Compensation/gifts/services", "k) Reimbursement", "l) Indemnity", "m) Record keeping period", "n) Confidentiality and secure storage", "o) Disclosure to third parties", "p) Privacy in publications", "q) Feedback to participants", "r) Confidentiality exclusions", "s) Audio/video consent"]},
                    {"name": "results_feedback", "label": "6.10 How will participants be informed of findings?", "type": "textarea"},
                    {"name": "products_access", "label": "6.11 Participants' access to products developed from the study", "type": "textarea"},
                    {"name": "publication_plans", "label": "6.12 Indicate how you envisage publishing this research", "type": "textarea"},
                    {"name": "participant_comp", "label": "6.13 Compensation to participants", "type": "textarea"},
                    {"name": "participant_costs", "label": "6.14 Financial costs to participants", "type": "textarea"},
                    {"name": "ethics_reporting", "label": "6.15 Reporting to ethics research committee", "type": "textarea"},
                ],
            },
            {
                "title": "Section 7: Declaration",
                "fields": [
                    {"name": "declaration_name", "label": "I, declaration name", "type": "text", "required": True},
                    {"name": "applicant_signature", "label": "Signature of Applicant", "type": "text", "required": True},
                    {"name": "declaration_date", "label": "Date", "type": "date", "required": True},
                ],
            },
        ],
    },
    "B": {
        "title": "Form B: Collecting secondary data only (e.g. reports, documents)",
        "templates": [
            ("Permission/Waiver and Declaration", "docs/JBSREC_apstone_Consulting_Project_Waiver_and_Declaration.docx"),
            ("Personal Impact Assessment Form And POPIA Consent Template", "docs/PIIA, POPIA consent and justification of collection of personal information.docx"),
            ("POPIA Information Letter and Consent Form", "docs/POPIA Information Letter and Consent Form_2025.docx"),
        ],
        "sections": [
            {"title": "Before You Start Form B", "fields": [
                {"name": "need_permission", "label": "1. Do you require permission to access the secondary data?", "type": "radio", "options": ["Yes", "No", "Pending"]},
                {"name": "permission_letter_path", "label": "Upload Permission Letter(s)", "type": "file", "multiple": True, "required": True, "show_when": {"field": "need_permission", "values": ["Yes"]}},
                {"name": "pending_note_path", "label": "Upload Pending Note (briefly explain who you contacted and expected timeline)", "type": "file", "required": True, "show_when": {"field": "need_permission", "values": ["Pending"]}},
                {"name": "has_clearance", "label": "2. Do you have prior ethical clearance for the original study?", "type": "radio", "options": ["Yes", "No"]},
                {"name": "prior_clearance_path", "label": "Upload Prior Ethical Clearance Document", "type": "file", "required": True, "show_when": {"field": "has_clearance", "values": ["Yes"]}},
                {"name": "proposal_path", "label": "3. Upload Approved Proposal", "type": "file", "required": True},
                {"name": "company_requires_jbs", "label": "4. Do you have access to personal information?", "type": "radio", "options": ["Yes", "No"]},
                {"name": "prior_clearance1", "label": "Upload POPIA Information Letter and Consent Form", "type": "file", "required": True, "show_when": {"field": "company_requires_jbs", "values": ["Yes"]}},
            ]},
            {"title": "Section 1: Researcher's Details", "fields": [
                {"name": "applicant_name", "label": "Applicant Name", "type": "text", "required": True},
                {"name": "student_number", "label": "Student/Staff Number", "type": "text", "required": True},
                {"name": "institution", "label": "Institution", "type": "text", "default": "University of Johannesburg", "required": True},
                {"name": "department", "label": "UJ Department and School", "type": "text", "required": True},
                {"name": "degree", "label": "Degree Registered For", "type": "text", "default": "MBA", "required": True},
                {"name": "study_title", "label": "Title/Working Title of Project or Study", "type": "text", "required": True},
                {"name": "mobile", "label": "Mobile Number", "type": "tel", "required": True},
            ]},
            {"title": "Section 2: Research Project and Data Information", "fields": [
                {"name": "project_description", "label": "2.1 Provide short description of the research project (+-200 words)", "type": "textarea", "required": True},
                {"name": "data_nature", "label": "2.2 What is the nature of the data?", "type": "text", "required": True},
                {"name": "data_origin", "label": "2.3 What is the origin/source of the research data?", "type": "text", "required": True},
                {"name": "data_public", "label": "2.4 Are the sources of the research data in the public domain?", "type": "radio", "options": ["Yes", "No"]},
                {"name": "public_evidence", "label": "2.4.1 Provide explanation", "type": "textarea", "required": True, "show_when": {"field": "data_public", "values": ["No"]}},
                {"name": "access_conditions", "label": "2.4.2 If the data is in the public domain, what are the access conditions?", "type": "textarea", "show_when": {"field": "data_public", "values": ["Yes"]}},
                {"name": "personal_info", "label": "2.5 Does the database contain personal information/identifiers?", "type": "radio", "options": ["Yes", "No"]},
                {"name": "personal_info_comment", "label": "If yes, specify what kind of personal information/identifiers will be collected", "type": "textarea", "required": True, "show_when": {"field": "personal_info", "values": ["Yes"]}},
                {"name": "data_anonymized", "label": "2.6 Do you have evidence that the data have been anonymized?", "type": "radio", "options": ["Yes", "No", "Not Applicable"]},
                {"name": "anonymization_comment", "label": "2.6.1 Comment / Justification", "type": "textarea"},
                {"name": "private_permission", "label": "2.7 Does private data contain information requiring permission?", "type": "radio", "options": ["Yes", "No"]},
                {"name": "permission_details", "label": "2.7.1 Provide permission details", "type": "textarea", "required": True, "show_when": {"field": "private_permission", "values": ["Yes"]}},
                {"name": "private_permission_file", "label": "Upload permission document (if applicable)", "type": "file", "show_when": {"field": "private_permission", "values": ["Yes"]}},
                {"name": "shortcomings_reported", "label": "2.8 Will data shortcomings/incompleteness be reported?", "type": "radio", "options": ["Yes", "No"]},
                {"name": "limitations_reporting", "label": "2.9 Explain how data limitations will be reported or why not", "type": "textarea"},
                {"name": "methodology_alignment", "label": "2.10 Are methodology and design aligned with preceding answers?", "type": "radio", "options": ["Yes", "No"]},
                {"name": "methodology_alignment_comment", "label": "If no, justify your answer", "type": "textarea", "required": True, "show_when": {"field": "methodology_alignment", "values": ["No"]}},
                {"name": "data_acknowledgment", "label": "2.11 How will original data owners be recognised/referenced/acknowledged?", "type": "textarea"},
            ]},
            {"title": "Section 3: Ethical Considerations", "fields": [
                {"name": "original_clearance", "label": "3.1 Was ethical clearance granted for the original data gathering phase?", "type": "radio", "options": ["Yes", "No", "Unknown"]},
                {"name": "participant_permission", "label": "3.2 Did participants grant permission for future use of the data?", "type": "radio", "options": ["Yes", "No", "Unknown"]},
                {"name": "data_safekeeping", "label": "3.3 If data is not public, explain safe storage and destruction", "type": "textarea"},
                {"name": "risk_level", "label": "3.4.1 The study presents", "type": "radio", "options": ["Low Risk", "Medium Risk", "High Risk"]},
                {"name": "risk_comments", "label": "3.4.2 Comments/Justification", "type": "textarea"},
            ]},
            {"title": "Section 4: Declaration", "fields": [
                {"name": "declaration_name", "label": "I, declaration name", "type": "text", "required": True},
                {"name": "full_name", "label": "Full Name", "type": "text", "required": True},
                {"name": "declaration_date", "label": "Date", "type": "date", "required": True},
            ]},
        ],
    },
    "C": {
        "title": "Form C: Requesting exemption (no human interaction or data collection)",
        "templates": [],
        "sections": [
            {"title": "Upload Proposal for Ethics Exemption (Form C)", "fields": [
                {"name": "proposal", "label": "Upload Your Research Proposal", "type": "file", "required": True},
            ]},
            {"title": "Section 1: Researcher's Details", "fields": [
                {"name": "applicant_name", "label": "Applicant Name", "type": "text", "required": True},
                {"name": "student_number", "label": "Student/Staff Number", "type": "text", "required": True},
                {"name": "institution", "label": "Institution", "type": "text", "default": "University of Johannesburg", "required": True},
                {"name": "department", "label": "UJ Department and School", "type": "text", "required": True},
                {"name": "degree", "label": "Degree Registered For", "type": "text", "default": "MBA", "required": True},
                {"name": "project_title", "label": "Title/Working Title of Study", "type": "text", "required": True},
                {"name": "mobile_number", "label": "Mobile Number", "type": "tel", "required": True},
            ]},
            {"title": "Section 2: Risk Assessment", "fields": [
                {"name": "vulnerable_groups", "label": "2.1 Vulnerable populations", "type": "checkboxes", "options": ["Communities that may be considered vulnerable", "People under 18 or over 65", "UJ employees or students", "Persons vulnerable in this context", "Non-English-speaking participants", "Researcher's own students", "People living in poverty", "People with little or no education", "Other"]},
                {"name": "vulnerable_other_description", "label": "Other vulnerable population: describe", "type": "textarea", "show_when": {"field": "vulnerable_groups", "values": ["Other"]}},
                {"name": "vulnerable_comments", "label": "Comments", "type": "textarea"},
                {"name": "research_activities", "label": "2.2 Research activities risk assessment", "type": "checkboxes", "options": ["Collection/use/disclosure without consent", "Discomfiture beyond normal inconvenience", "Deception or covert observation", "Sensitive or contentious issues", "Prejudicial information", "Intrusive techniques", "Illegal activities", "Direct personal/social information", "Identifiable available records", "Psychology inventories/scales/tests", "Researcher/data collector risk", "Other"]},
                {"name": "activity_other_description", "label": "Other activity: describe", "type": "textarea", "show_when": {"field": "research_activities", "values": ["Other"]}},
                {"name": "activity_comments", "label": "Comments", "type": "textarea"},
                {"name": "additional_considerations", "label": "2.3 Additional research considerations", "type": "checkboxes", "options": ["Reimbursement or incentives", "Financial costs to participants", "Researcher financial or other involvement", "Conflict of interest", "Conducted on UJ premises", "Uses UJ facilities", "Funded by UJ or UJ-acquired funding"]},
                {"name": "consideration_comments", "label": "Comments", "type": "textarea"},
                {"name": "risk_level", "label": "Rate your project risk level", "type": "select", "options": ["Low Risk", "Medium Risk", "High Risk"], "required": True},
                {"name": "risk_justification", "label": "2.4.1 Justify the Risk Level", "type": "textarea", "required": True},
            ]},
            {"title": "Section 3: Proposal Summary Sheet", "fields": [
                {"name": "summary_title", "label": "3.1 Title or Provisional Title of the Research Project", "type": "text", "required": True},
                {"name": "executive_summary", "label": "3.2 Executive Summary of the Study", "type": "textarea", "required": True},
                {"name": "research_questions", "label": "3.3 Research Questions / Hypotheses", "type": "textarea", "required": True},
                {"name": "research_purpose", "label": "3.4 Research Purpose and Objectives / Anticipated Outcomes", "type": "textarea", "required": True},
                {"name": "secondary_data_info", "label": "3.5 Secondary Data: how was data originally collected, and how were ethical aspects handled?", "type": "textarea", "required": True},
                {"name": "exemption_reason", "label": "3.6 Why does your study meet exemption requirements?", "type": "textarea", "required": True},
            ]},
            {"title": "Section 4: Declaration", "fields": [
                {"name": "declaration_name", "label": "I, declaration name", "type": "text", "required": True},
                {"name": "full_name", "label": "Full Name", "type": "text", "required": True},
                {"name": "submission_date", "label": "Date", "type": "date", "required": True},
            ]},
        ],
    },
}


def form_definition(form_type):
    return FORM_DEFINITIONS.get((form_type or "").upper())


def iter_fields(definition):
    for section in definition["sections"]:
        for field in section["fields"]:
            yield section, field
