"""add discipline_id

Revision ID: 40c8fdf09260
Revises: 
Create Date: 2026-04-28 14:40:33.170465

"""
from alembic import op
import sqlalchemy as sa

from migrations.schema_helpers import add_column_if_missing, create_foreign_key_if_missing


# revision identifiers, used by Alembic.
revision = '40c8fdf09260'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    add_column_if_missing('mba_projects', sa.Column('discipline_id', sa.Integer(), nullable=True))
    add_column_if_missing(
        'mba_projects',
        sa.Column('assignment_confirmed', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    add_column_if_missing('mba_projects', sa.Column('invitations_sent_at', sa.DateTime(), nullable=True))
    add_column_if_missing('mba_projects', sa.Column('primary_supervisor_invitation_status', sa.String(length=20), nullable=True))
    add_column_if_missing('mba_projects', sa.Column('assessor_1_invitation_status', sa.String(length=20), nullable=True))
    add_column_if_missing('mba_projects', sa.Column('assessor_2_invitation_status', sa.String(length=20), nullable=True))
    add_column_if_missing('mba_projects', sa.Column('assessor_3_invitation_status', sa.String(length=20), nullable=True))
    add_column_if_missing('mba_projects', sa.Column('supervisor_accepted_at', sa.DateTime(), nullable=True))
    add_column_if_missing(
        'mba_projects',
        sa.Column('supervisor_confirmed', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    add_column_if_missing(
        'mba_projects',
        sa.Column('assessors_confirmed', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    create_foreign_key_if_missing(
        'fk_mba_projects_discipline_id_mba_disciplines',
        'mba_projects',
        'mba_disciplines',
        ['discipline_id'],
        ['id'],
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mba_projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assessors_confirmed')
        batch_op.drop_column('supervisor_confirmed')
        batch_op.drop_column('supervisor_accepted_at')
        batch_op.drop_column('assessor_3_invitation_status')
        batch_op.drop_column('assessor_2_invitation_status')
        batch_op.drop_column('assessor_1_invitation_status')
        batch_op.drop_column('primary_supervisor_invitation_status')
        batch_op.drop_column('invitations_sent_at')
        batch_op.drop_column('assignment_confirmed')
        batch_op.drop_column('discipline_id')

    # ### end Alembic commands ###
