"""empty message

Revision ID: 8697bc60bdb4
Revises: c5d6e7f8a9b0
Create Date: 2026-05-19 03:33:27.909531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8697bc60bdb4'
down_revision = 'c5d6e7f8a9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mba_projects', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['module_completion_verification_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mba_projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
