"""empty message

Revision ID: a26f9f092cc3
Revises: d900ddf35d3a
Create Date: 2026-05-26 13:21:53.144976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26f9f092cc3'
down_revision = 'd900ddf35d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mba_booking_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['mba_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_mba_booking_day_date')
    )
    with op.batch_alter_table('mba_booking_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mba_booking_days_date'), ['date'], unique=False)

    op.create_table('mba_booking_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_released', sa.Boolean(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('released_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['released_by_id'], ['mba_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mba_booking_panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['mba_booking_days.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_id', 'name', name='uq_mba_booking_panel_day_name')
    )
    with op.batch_alter_table('mba_booking_panels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mba_booking_panels_day_id'), ['day_id'], unique=False)

    op.create_table('mba_booking_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role in ('student','supervisor')", name='mba_booking_slot_role_check'),
    sa.ForeignKeyConstraint(['day_id'], ['mba_booking_days.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_id', 'role', 'label', name='uq_mba_booking_slot_day_role_label')
    )
    with op.batch_alter_table('mba_booking_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mba_booking_slots_day_id'), ['day_id'], unique=False)

    op.create_table('mba_panel_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('surname', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('co_supervisor_id', sa.Integer(), nullable=True),
    sa.Column('co_supervisor_name', sa.String(length=255), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('booked_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role in ('student','supervisor')", name='mba_panel_booking_role_check'),
    sa.CheckConstraint("status in ('active','cancelled')", name='mba_panel_booking_status_check'),
    sa.ForeignKeyConstraint(['co_supervisor_id'], ['mba_users.id'], ),
    sa.ForeignKeyConstraint(['day_id'], ['mba_booking_days.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['mba_booking_panels.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['mba_booking_slots.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['mba_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['mba_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mba_panel_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mba_panel_bookings_day_id'), ['day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mba_panel_bookings_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_mba_panel_bookings_panel_id'), ['panel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mba_panel_bookings_slot_id'), ['slot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mba_panel_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mba_panel_bookings_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('mba_project_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_mba_project_documents_project_doc_type'))

    with op.batch_alter_table('mba_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_mba_projects_module_completion_token'), postgresql_where='(module_completion_verification_token IS NOT NULL)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mba_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_mba_projects_module_completion_token'), ['module_completion_verification_token'], unique=True, postgresql_where='(module_completion_verification_token IS NOT NULL)')

    with op.batch_alter_table('mba_project_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_mba_project_documents_project_doc_type'), ['project_id', 'doc_type'], unique=True)

    with op.batch_alter_table('mba_panel_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mba_panel_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_mba_panel_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_mba_panel_bookings_slot_id'))
        batch_op.drop_index(batch_op.f('ix_mba_panel_bookings_panel_id'))
        batch_op.drop_index(batch_op.f('ix_mba_panel_bookings_email'))
        batch_op.drop_index(batch_op.f('ix_mba_panel_bookings_day_id'))

    op.drop_table('mba_panel_bookings')
    with op.batch_alter_table('mba_booking_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mba_booking_slots_day_id'))

    op.drop_table('mba_booking_slots')
    with op.batch_alter_table('mba_booking_panels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mba_booking_panels_day_id'))

    op.drop_table('mba_booking_panels')
    op.drop_table('mba_booking_settings')
    with op.batch_alter_table('mba_booking_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mba_booking_days_date'))

    op.drop_table('mba_booking_days')
    # ### end Alembic commands ###
