"""empty message

Revision ID: d900ddf35d3a
Revises: b4e6f8a1c2d3
Create Date: 2026-05-19 07:35:15.869411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd900ddf35d3a'
down_revision = 'b4e6f8a1c2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mba_project_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_mba_project_documents_project_doc_type'))

    with op.batch_alter_table('mba_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_mba_projects_module_completion_token'), postgresql_where='(module_completion_verification_token IS NOT NULL)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mba_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_mba_projects_module_completion_token'), ['module_completion_verification_token'], unique=True, postgresql_where='(module_completion_verification_token IS NOT NULL)')

    with op.batch_alter_table('mba_project_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_mba_project_documents_project_doc_type'), ['project_id', 'doc_type'], unique=True)

    # ### end Alembic commands ###
